/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import dao.ItemPedidoDAO;
import dao.PedidoDAO;
import dao.ProdutoDAO;
import entidade.Item_pedido;
import entidade.Pedido;
import entidade.Produto;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class IfrPedido extends javax.swing.JInternalFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    int ID = 0;

    public IfrPedido() {
        initComponents();
        GetAllData();
        GetAllProductData();

        Formatacao.formatarData(tfdData);
        new CombosDAO().popularCombo("cliente", cmbCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdObservacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfdData = new javax.swing.JFormattedTextField();
        cmbCliente = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPed = new javax.swing.JTable();
        jButtonEdit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboFornecedor = new javax.swing.JComboBox<>();
        tfdBusca = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setTitle("Cadastro: Pedido");

        jButtonClose.setText("Fechar");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Endereço de entrega", "Observação", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPedido);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jLabel1.setText("Data");

        jLabel2.setText("Endereço de entrega");

        jLabel4.setText("Observação");

        jLabel5.setText("Cliente");

        tfdData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdDataFocusLost(evt);
            }
        });

        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDel.setText("DEL");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jLabel6.setText("Produtos");

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descricao", "Valor und.", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblProd);

        tblPed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descricao", "Valor und.", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPed);

        jButtonEdit.setText("EDIT");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(52, 52, 52)
                            .addComponent(tfdObservacao))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfdEndereco))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(77, 77, 77)
                            .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(90, 90, 90)
                            .addComponent(tfdData, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfdObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEdit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Inserção", jPanel2);

        jLabel3.setText("Buscar");

        jComboFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Endereço", "Observação" }));
        jComboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFornecedorActionPerformed(evt);
            }
        });

        tfdBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdBuscaActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Pesquisar");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(200, 0, 0));
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(btnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSearch)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditar)
                        .addComponent(btnDeletar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonClose)
                        .addComponent(btnSalvar)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        int linha = tblProd.getSelectedRow();
        
        DefaultTableModel modelProdutos =
            (DefaultTableModel) tblProd.getModel();

        int ID = Integer.parseInt(
            modelProdutos.getValueAt(linha, 0).toString()
        );
        
        String descricao = modelProdutos.getValueAt(linha, 1).toString();

        float valor = Float.parseFloat(
            modelProdutos.getValueAt(linha, 2).toString()
        );

        int estoque = Integer.parseInt(
            modelProdutos.getValueAt(linha, 3).toString()
        );
        
        String qtdTexto = JOptionPane.showInputDialog(
            this,
            "Informe a quantidade:"
        );

        if (qtdTexto == null)
            return;
        
        int quantidade = Integer.parseInt(qtdTexto);

        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(
                this,
                "Quantidade inválida."
            );
            return;
        }

        if (quantidade > estoque) {
            JOptionPane.showMessageDialog(
                this,
                "Quantidade superior ao estoque."
            );
            return;
        }
        
        DefaultTableModel modelPedido =
            (DefaultTableModel) tblPed.getModel();

        modelPedido.addRow(new Object[]{
            ID,
            descricao,
            valor,
            quantidade
        });
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        int linha = tblPed.getSelectedRow();

        if (linha >= 0) {

            ((DefaultTableModel) tblPed.getModel())
                .removeRow(linha);

            tblPed.remove(linha);
        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void tblPedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedMouseClicked
    }//GEN-LAST:event_tblPedMouseClicked

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        int linha = tblPed.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um item.");
            return;
        }

        String atual = tblPed.getValueAt(linha, 3).toString();

        String novaQtd = JOptionPane.showInputDialog(
                this,
                "Nova quantidade:",
                atual);

        if (novaQtd == null)
            return;

        try {

            int qtd = Integer.parseInt(novaQtd);

            if (qtd <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Quantidade inválida.");
                return;
            }

            tblPed.setValueAt(qtd, linha, 3);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Digite apenas números.");

        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void tfdDataFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_tfdDataFocusLost
        // TODO add your handling code here:
    }// GEN-LAST:event_tfdDataFocusLost

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSearchActionPerformed
        ArrayList<Pedido> p = new ArrayList();
        String criterio = jComboFornecedor.getSelectedItem().toString();
        String valor = tfdBusca.getText();

        if (valor.isEmpty())
            GetAllData();
        else {
            p = new PedidoDAO().consultar(criterio, valor);
            ExibitData(p);
        }
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {

        if (tfdData.getText().isEmpty()
                || tfdEndereco.getText().isEmpty()
                || tfdObservacao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não foi possível inserir os dados.");
            tfdData.requestFocus();
            return;
        }

        ComboItem ci = (ComboItem) cmbCliente.getSelectedItem();
        if (ci == null || ci.getCodigo() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente.");
            cmbCliente.requestFocus();
            return;
        }
        
        int rows = tblPed.getRowCount();

        Pedido p = new Pedido(
                ID,
                parseData(tfdData.getText()),
                tfdEndereco.getText(),
                tfdObservacao.getText(),
                ci.getCodigo());

        PedidoDAO pedidoDAO = new PedidoDAO();
        ItemPedidoDAO itemDAO = new ItemPedidoDAO();

        int idGerado = -1;
        String logRegistro = null;

        if (ID == 0) {
            idGerado = Integer.parseInt(pedidoDAO.salvar(p));
            logRegistro = "Registro salvo com sucesso! ID: " + idGerado;
        } else {
            idGerado = Integer.parseInt(pedidoDAO.atualizar(p));
            logRegistro = "Registro atualizado com sucesso!";
        }

        if (idGerado >= 0) {
            for (int x = 0; x < rows; x++){
               itemDAO.salvar(new Item_pedido(
                       0,
                       ID,
                       Integer.parseInt(tblPed.getValueAt(x, 0).toString()),
                       Double.parseDouble(tblPed.getValueAt(x, 3).toString()),
                       Float.parseFloat(tblPed.getValueAt(x, 2).toString())
                )
               );
            }
            
            ClearAllData();
            GetAllData();
            tblPedido.requestFocus();

            JOptionPane.showMessageDialog(this, logRegistro);
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao salvar registro! " + idGerado);
        }
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {
        String idTabela = String.valueOf(tblPedido.getValueAt(tblPedido.getSelectedRow(), 0));

        Pedido p = new PedidoDAO().consultarId(Integer.parseInt(idTabela));

        ID = p.id;

        if (p != null) {
            jTabbedPane1.setSelectedIndex(1);

            tfdData.setText(sdf.format(p.data));
            tfdEndereco.setText(p.endereco_entrega);
            tfdObservacao.setText(p.observacao);
            ComboItem item = new ComboItem();
            item.setCodigo(p.cliente_id);
            new CombosDAO().definirItemCombo(cmbCliente, item);

            tfdData.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id da cidade não encontrado!");
        }
    }

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<Pedido> p = new ArrayList();
        String idTabela = String.valueOf(tblPedido.getValueAt(tblPedido.getSelectedRow(), 0));

        ID = Integer.parseInt(idTabela);

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir este registro?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            try {
                new PedidoDAO().excluir(ID);
                JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Problemas ao excluir registro!");
            }

            jTabbedPane1.setSelectedIndex(0);
            ClearAllData();
            GetAllData();
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir registro!");
        }
        ID = 0;
    }

    private void tfdDataActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfdDataActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfdDataActionPerformed

    private void jComboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboFornecedorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboFornecedorActionPerformed

    private void tfdBuscaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfdBuscaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfdBuscaActionPerformed

    private java.util.Date parseData(String valor) {
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(valor);
        } catch (Exception e) {
            return null;
        }
    }

    private void GetAllData() {
        ArrayList<Pedido> p = new ArrayList();

        p = new PedidoDAO().consultarTodos();

        ExibitData(p);
    }

    private void ClearAllData() {
        tfdData.setText("");
        tfdEndereco.setText("");
        tfdObservacao.setText("");
        cmbCliente.setSelectedIndex(0);
    }

    private void ExibitData(ArrayList<Pedido> p) {
        for (Pedido x : p) {
            System.out.println("Id: " + x.id);
            System.out.println("Data: " + sdf.format(x.data));
            System.out.println("Endereço Entrega: " + x.endereco_entrega);
            System.out.println("Observação: " + x.observacao);
            System.out.println("Cliente: " + x.cliente_nome);
            System.out.println("");
        }

        DefaultTableModel modelo = (DefaultTableModel) tblPedido.getModel();
        modelo.setRowCount(0);

        for (Pedido x : p) {
            modelo.addRow(new Object[] {
                    x.id,
                    sdf.format(x.data),
                    x.endereco_entrega,
                    x.observacao,
                    x.cliente_nome
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPed;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTable tblProd;
    private javax.swing.JTextField tfdBusca;
    private javax.swing.JFormattedTextField tfdData;
    private javax.swing.JTextField tfdEndereco;
    private javax.swing.JTextField tfdObservacao;
    // End of variables declaration//GEN-END:variables

    private void GetAllProductData() {
        DefaultTableModel pedido = (DefaultTableModel) tblPed.getModel();
        pedido.setRowCount(0);
        
        ArrayList<Produto> p = new ArrayList();

        p = new ProdutoDAO().consultarTodos();

        DefaultTableModel modelo = (DefaultTableModel) tblProd.getModel();
        modelo.setRowCount(0);

        for (Produto x : p) {
            modelo.addRow(new Object[] {
                x.id,
                x.descricao,
                x.valor_unitario,
                x.qtde_estoque
            });
        }
    }
}
